name: todo_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  connectivity_plus: ^7.0.0
  dio: ^5.9.1
  equatable: ^2.0.8
  flutter:
    sdk: flutter
  flutter_jailbreak_detection_plus: ^1.10.7
  flutter_riverpod: ^3.2.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  sqflite: ^2.4.2
  uuid: ^4.5.2

  path: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
